# Site settings
author: Kevin Hong
title: KHong Codes
header-img: img/home-bg.png
email: albtrossfacefall@gmail.com
copyright_name: Kevin Hong
description: > # this means to ignore newlines until "baseurl:"
  On Doing Making and Making Do
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  khongcodes2

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
